src/manager/urls.py
""" Manager app urls module """

from django.urls import path

from .views import IndexView, ProductsManagementView, \
    ProductEditView, ProductDeleteView, CategoriesManagementView, \
    CategoryEditView, CategoryDeleteView

app_name = 'manager'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),

    path('categories/', CategoriesManagementView.as_view(), name='categories'),
    path(
        'category-create/', CategoryEditView.as_view(), name='category-create'
    ),
    path(
        'category-edit/<int:id>/', CategoryEditView.as_view(),
        name='category-edit'
    ),
    path(
        'category-delete/<int:pk>/', CategoryDeleteView.as_view(),
        name='category-delete'
    ),

    path('products/', ProductsManagementView.as_view(), name='products'),
    path('product-create/', ProductEditView.as_view(), name='product-create'),
    path(
        'product-edit/<slug:slug>/', ProductEditView.as_view(),
        name='product-edit'
    ),
    path(
        'product-delete/<slug:slug>/', ProductDeleteView.as_view(),
        name='product-delete'
    ),
]

src/pyshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from pyshop import settings


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('website.urls')),
    path('manager/', include('manager.urls')),

    path('api/', include('restapi.urls')),
]

# enable permissions to read media folder
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/website/urls.py
""" website's urls module """

from django.urls import path

from .views import ProductsView, SignInView, SignOutView, SignUpView, \
    AddToCartView, ProductDetailView, ProfileView, PurchaseOrdersView, \
    PurchaseOrderDetailView, CompletePurchaseOrderView


app_name = 'website'

urlpatterns = [
    path('', ProductsView.as_view(), name='index'),

    path('signin/', SignInView.as_view(), name='signin'),
    path('signout/', SignOutView.as_view(), name='signout'),
    path('signup/', SignUpView.as_view(), name='signup'),

    path(
        'purchase-orders/', PurchaseOrdersView.as_view(),
        name='purchase-orders'
    ),
    path(
        'purchase-order/<int:id>/', PurchaseOrderDetailView.as_view(),
        name='purchase-order'
    ),
    path(
        'complete-purchase-order/<int:id>/',
        CompletePurchaseOrderView.as_view(),
        name='complete-purchase-order'
    ),
    path('profile/', ProfileView.as_view(), name='profile'),

    path(
        'products/<slug:slug>/', ProductDetailView.as_view(),
        name='product-detail'
    ),
    path('add-to-cart/', AddToCartView.as_view(), name='add-to-cart')
]

src/website/forms.py
""" website django forms """

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    """ Form for the users' registragion fields """

    first_name = forms.CharField(
        max_length=30, required=False, help_text='Optional.'
    )
    last_name = forms.CharField(
        max_length=30, required=False, help_text='Optional.'
    )
    email = forms.EmailField(
        max_length=254, help_text='Required. Inform a valid email address.'
    )

    class Meta:
        """ SignUpForm's Meta class """

        model = User
        fields = (
            'username', 'first_name', 'last_name',
            'email', 'password1', 'password2',
        )

src/website/views.py
""" website views module """

# pylint: disable=W0613, W0221


from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.views.generic import ListView, View, DetailView, TemplateView
from django.views.generic.edit import CreateView
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.utils.translation import ugettext

from .forms import SignUpForm
from .models import Category, Product, PurchaseOrder, PurchaseItem


class ProductsView(ListView):
    """ ListView that shows all of (or query) the products """

    template_name = 'products.html'
    context_object_name = 'product_list'

    def get_queryset(self):
        """ Returns the queryset of products and categories """

        queryset = Product.objects.all()

        category = self.request.GET.get('category', None)

        if category:
            queryset = queryset.filter(
                category__description=category
            )

        q = self.request.GET.get('q', None)

        if q:
            queryset = queryset.filter(
                Q(title__icontains=q) |
                Q(description__icontains=q)
            )

        return queryset

    def get_context_data(self, **kwargs):
        """ Mounts the context objects and verifies if user is authenticated
        """

        context = super(ProductsView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['authenticated_user'] = self.request.user
        context['categories'] = Category.objects.all()
        return context


class ProductDetailView(DetailView):
    """ DetailView for a specific (selected) product """

    template_name = 'product_detail.html'

    def get_object(self, *args, **kwargs):
        """ Returns the product instance by the slug field """

        slug = self.kwargs.get('slug')
        instance = get_object_or_404(Product, slug=slug)
        return instance

    def get_context_data(self, **kwargs):
        """ Mounts the context objects and verifies if user is authenticated
        """

        context = super(ProductDetailView, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['authenticated_user'] = self.request.user
        return context


class ProfileView(TemplateView):
    """ View for the users' profiles """

    template_name = 'profile.html'

    def get(self, request, *args, **kwargs):
        """ Check if user is authenticated, otherwise redirect to sigin page
        """

        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse_lazy('website:signin'))
        return render(
            request, self.template_name, self.get_context_data(**kwargs)
        )

    def get_context_data(self, **kwargs):
        """ Mounts the context objects (including user) """

        context = super(ProfileView, self).get_context_data(**kwargs)
        context['user'] = self.request.user
        return context


class PurchaseOrdersView(TemplateView):
    """ TemplateView for the user's purchase orders """

    template_name = 'purchase_orders.html'

    def get(self, request, *args, **kwargs):
        """ Verify if user is authenticated, otherwise redirect to sigin page
        """

        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse_lazy('website:signin'))
        return render(request, self.template_name, self.get_context_data())

    def get_context_data(self, **kwargs):
        """ Makes the purchase_orders list """

        context = super(PurchaseOrdersView, self).get_context_data(**kwargs)
        context['purchase_orders'] = PurchaseOrder.objects.all() \
            .order_by('id').order_by('-cart')
        return context


class PurchaseOrderDetailView(TemplateView):
    """ Shows the purchase order details """

    template_name = 'purchase_order_detail.html'

    def get_context_data(self, **kwargs):
        """ Makes the purchase_order object and the purchase_items list """

        context = super(PurchaseOrderDetailView, self).get_context_data(
            **kwargs
        )
        id = self.kwargs.get('id')
        purchase_order = get_object_or_404(PurchaseOrder, id=id)
        context['purchase_order'] = purchase_order
        purchase_items = PurchaseItem.objects.filter(
            purchase_order_id=purchase_order.id
        )
        if purchase_items.exists():
            context['purchase_items'] = purchase_items
        return context


class CompletePurchaseOrderView(DetailView):
    """ DetailView that changes the purchase order's status (to complete) """

    def get(self, request, *args, **kwargs):
        """ Receives the purchase order's id and changes the cart field to
        False, meaning that the purchase order is completed. After changing
        the status, redirect to the index page
        """
        id = self.kwargs.get('id')

        purchase_order = get_object_or_404(PurchaseOrder, id=id)
        purchase_order.cart = False
        purchase_order.save()

        return HttpResponseRedirect(reverse_lazy('website:index'))


class SignInView(TemplateView):
    """ TemplateView for the user's login """

    template_name = 'signin.html'

    def post(self, request, *args, **kwargs):  # pylint: disable=R0201
        """ Receives the username and password, tries to do the login, and
        then redirect to the index page
        """

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
            else:  # pragma: no cover
                messages.error(request, ugettext('UserIsInactive'))
        else:
            messages.error(request, ugettext('Invalidlogin'))
        return HttpResponseRedirect(reverse_lazy('website:index'))


class SignOutView(View):
    """ View for the user's logout """

    def get(self, request, *args, **kwargs):  # pylint: disable=R0201
        """ Sign the user out and then redirect to the previously accessed
        page
        """

        logout(request)
        previous_url = request.META.get('HTTP_REFERER')

        return HttpResponseRedirect(previous_url)


class SignUpView(CreateView):
    """ CreateView for the users' registration """

    template_name = 'signup.html'
    form_class = SignUpForm
    success_url = reverse_lazy('website:index')

    def form_valid(self, form):
        """ Check if form is valid and then save it """

        form.save()
        return super().form_valid(form)


class AddToCartView(View):
    """ View to add item to user's cart """

    def post(self, request, *args, **kwargs):
        """ Check if user is authenticated, otherwise redirect to the sigin
        Then it expects the product_id that the user wants to add to the cart.
        If the user doesn't have any pending purchase order (cart=True), a new
        order is created, with the new item, and the user is redirected to the
        previously accessed page.
        """

        previous_url = request.META.get('HTTP_REFERER')

        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse_lazy('website:signin'))

        product_id = request.POST.get('product_id', None)
        product = get_object_or_404(Product, barcode=product_id)

        user = self.request.user

        order_queryset = PurchaseOrder.objects.filter(
            Q(user=user) & Q(cart=True)
        )
        if order_queryset.exists():
            purchase_order = order_queryset.first()
        else:
            purchase_order = PurchaseOrder.objects.create(
                timestamp=timezone.now(), user=user, cart=True
            )

        PurchaseItem.objects.create(
            barcode=product.barcode, title=product.title,
            description=product.description, image=product.image,
            price=product.price, category=product.category,
            purchase_order=purchase_order, quantity=1.000,
            total_price=product.price
        )

        return HttpResponseRedirect(previous_url)

src/website/templates/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>
  {% block title %}
    PyShop
  {% endblock title %}
  </title>
  <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" />
</head>
<body>
  {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
  {% endif %}
  {% if authenticated_user %}
    <a href="{% url 'website:profile' %}">{% trans 'MyProfile' %}</a>
    <a href="{% url 'website:purchase-orders' %}">{% trans 'MyPurchases' %}</a>
    <a href="{% url 'website:signout' %}">{% trans 'SignOut' %}</a>
  {% else %}
    {% include 'signin.html' %}
  {% endif %}
  <hr/>
  <center>
    <a href="{% url 'manager:index' %}">{% trans 'Manager' %}</a>
  </center>
  <hr/>
  <center>
    <a href='{% url 'website:index' %}'>{% trans "HomePage" %}</a>
    {% for category in categories %}
      <a href="{% url 'website:index' %}?category={{ category.description }}">{{ category.description }}</a>&nbsp;
    {% endfor %}
  </center>
  {% block content %}
  {% endblock content %}
</body>
</html>

src/website/templates/product_detail.html
{% extends 'base.html' %}
{% load i18n %}
<hr/>
{% block title %}{% trans 'ProductsList' %}{% endblock title %}
 <form action="{% url 'website:index' %}">
    <label for="q">Search</label>
    <input type="text" name="q" id="q">
    <input type="submit" value="submit">
  </form>
  {% block content %}
    <hr/>
    <center>
    ID: {{ product.barcode }}<br/>
    {% trans 'Title' %}: {{ product.title }}<br/>
    {% trans 'Description' %}: {{ product.description }}<br/>
    <img src='{{ product.image.url }}' /><br/>
    {% trans 'Price' %}: US$ {{ product.price }}<br/>
    <form action="{% url 'website:add-to-cart' %}" method="post">
    	{% csrf_token %}
    	<input type="hidden" name="product_id" id="product_id" value="{{ product.barcode }}" />
    	<input type="submit" name="add_cart_submit" id="add_cart_submit" value="{% trans 'AddToCart' %}" />
    </form>
    <hr/>    
    </center>
  {% endblock content%}

src/website/templates/products.html
{% extends 'base.html' %}
{% load i18n %}
<hr/>
{% block title %}{% trans 'ProductsList' %}{% endblock title %}
<form action="{% url 'website:index' %}">
  <label for="q">Search</label>
  <input type="text" name="q" id="q">
  <input type="submit" value="submit">
</form>
{% block content %}
  <hr/>
  <center>
  <h1>{% trans 'ProductsList' %}</h1>
  {% for product in product_list %}
    {{ product.barcode }}<br/>
    {{ product.title }}<br/>
    <img src="{{ product.image.url }}" /><br/>
    US$ {{ product.price }}<br/>
    <a href="{{ product.get_absolute_url }}">{% trans 'Details' %}</a>
    <form action="{% url 'website:add-to-cart' %}" method="post">
    	{% csrf_token %}
    	<input type="hidden" name="product_id" id="product_id" value="{{ product.barcode }}" />
    	<input type="submit" name="add_cart_submit" id="add_cart_submit" value="{% trans 'AddToCart' %}" />
    </form>
    <hr/>
  {% endfor %}
  </center>
{% endblock content%}

src/website/templates/profile.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>
  {% block title %}
    {% trans 'MyProfile' %}
  {% endblock title %}
  </title>
  <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" />
</head>
<body>
  {% block content %}
    {% trans 'FirstName' %}: {{ user.username }}<br/>
    {% trans 'LastName' %}: {{ user.username }}<br/>
    Email: {{ user.username }}
  {% endblock content %}
</body>
</html>

src/website/templates/purchase_order_detail.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>
  {% block title %}
    {% trans 'MyPurchases' %}
  {% endblock title %}
  </title>
  <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" />
</head>
<body>
  {% block content %}
    ID: {{ purchase_order.id }}<br/>
    Date: {{ purchase_order.timestamp }}<br/>
    {% if purchase_order.cart is True %}
      {% trans 'Pending' %}
    {% else %}
      {% trans 'Completed' %}
    {% endif %}<br/>
    <a href="{% url 'website:complete-purchase-order' purchase_order.id %}">Complete Purchase Order</a><br/>
    <table border="1px">
      <tr>
        <th>ID</th>
        <th>Title</th>
      </tr>
      {% for purchase_item in purchase_items %}
      <tr>
        <td>{{ purchase_item.id }}</td>
        <td>{{ purchase_item.title }}</td>
      </tr>
      {% endfor %}
    </table>
  {% endblock content %}
</body>
</html>

src/website/templates/purchase_orders.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>
  {% block title %}
    {% trans 'MyPurchases' %}
  {% endblock title %}
  </title>
  <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" />
</head>
<body>
  {% block content %}
    {% for purchase_order in purchase_orders %}
      <a href="{% url 'website:purchase-order' purchase_order.id %}">ID: {{ purchase_order.id }}</a>
      - Date: {{ purchase_order.timestamp }}
      {% if purchase_order.cart is True %}
        {% trans 'Pending' %}
      {% else %}
        {% trans 'Completed' %}
      {% endif %}
      <br/>
    {% endfor %}
  {% endblock content %}
</body>
</html>

src/website/templates/signin.html
{% load i18n %}
{% load static %}
<form action="{% url 'website:signin' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <label for="username">{% trans 'Username' %}:</label>
  <input type="text" name="username" id="username">
  <label for="password">{% trans 'Password' %}:</label>
  <input type="password" name="password" id="password">
  <input type="submit" name="submit" value="{% trans 'SignIn' %}">
  <a href='{% url 'website:signup' %}'>{% trans 'SignUp' %}</a>
</form>

src/website/templates/signup.html
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
  <title>PyShop</title>
</head>
<body>
  <hr/>
    <div class="login">
         {% if messages %}
            <ul>
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
         <form method="post" >
             {% csrf_token %}
             <table>
                {{ form.as_p }}
                 <tr>
                    <td></td>
                    <td><input type="submit" name="submit" value="{% trans 'SignUp' %}" /></td>
                </tr>
             </table>
         </form>
     </div>
  <hr/>
</body>
</html>