src/manager/urls.py
""" Manager app urls module """

from django.urls import path

from .views import IndexView, ProductsManagementView, \
    ProductEditView, ProductDeleteView, CategoriesManagementView, \
    CategoryEditView, CategoryDeleteView

app_name = 'manager'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),

    path('categories/', CategoriesManagementView.as_view(), name='categories'),
    path(
        'category-create/', CategoryEditView.as_view(), name='category-create'
    ),
    path(
        'category-edit/<int:id>/', CategoryEditView.as_view(),
        name='category-edit'
    ),
    path(
        'category-delete/<int:pk>/', CategoryDeleteView.as_view(),
        name='category-delete'
    ),

    path('products/', ProductsManagementView.as_view(), name='products'),
    path('product-create/', ProductEditView.as_view(), name='product-create'),
    path(
        'product-edit/<slug:slug>/', ProductEditView.as_view(),
        name='product-edit'
    ),
    path(
        'product-delete/<slug:slug>/', ProductDeleteView.as_view(),
        name='product-delete'
    ),
]

src/pyshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from pyshop import settings


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('website.urls')),
    path('manager/', include('manager.urls')),

    path('api/', include('restapi.urls')),
]

# enable permissions to read media folder
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/website/urls.py
""" website's urls module """

from django.urls import path

from .views import ProductsView, SignInView, SignOutView, SignUpView, \
    AddToCartView, ProductDetailView, ProfileView, PurchaseOrdersView, \
    PurchaseOrderDetailView, CompletePurchaseOrderView


app_name = 'website'

urlpatterns = [
    path('', ProductsView.as_view(), name='index'),

    path('signin/', SignInView.as_view(), name='signin'),
    path('signout/', SignOutView.as_view(), name='signout'),
    path('signup/', SignUpView.as_view(), name='signup'),

    path(
        'purchase-orders/', PurchaseOrdersView.as_view(),
        name='purchase-orders'
    ),
    path(
        'purchase-order/<int:id>/', PurchaseOrderDetailView.as_view(),
        name='purchase-order'
    ),
    path(
        'complete-purchase-order/<int:id>/',
        CompletePurchaseOrderView.as_view(),
        name='complete-purchase-order'
    ),
    path('profile/', ProfileView.as_view(), name='profile'),

    path(
        'products/<slug:slug>/', ProductDetailView.as_view(),
        name='product-detail'
    ),
    path('add-to-cart/', AddToCartView.as_view(), name='add-to-cart')
]

src/manager/forms.py
""" Manager app forms module """

from django import forms

from website.models import Category, Product


class CategoryEditForm(forms.ModelForm):
    """ ModelForm for the Category model administration """

    class Meta:
        """ CategoryEditForm's Meta class """

        model = Category
        fields = ['description']


class ProductEditForm(forms.ModelForm):
    """ ModelForm for the Product model administration """

    class Meta:
        """ ProductEditForm's Meta class """

        model = Product
        fields = [
            'barcode', 'title', 'description',
            'image', 'price', 'category'
        ]

src/manager/views.py
""" Manager app views module """

from django.shortcuts import get_object_or_404

from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, TemplateView, \
    DeleteView

from website.models import Category, Product
from .forms import CategoryEditForm, ProductEditForm


class IndexView(TemplateView):
    """ Manager app view for the main page """

    template_name = 'index.html'


class CategoriesManagementView(ListView):
    """ ListView for the Category model administration """

    template_name = 'categories_management.html'
    context_object_name = 'categories'

    def get_queryset(self):
        """ Returns the list of category instances """

        queryset = Category.objects.all()
        return queryset


class CategoryEditView(UpdateView):
    """ View for editing a specific category instance """

    template_name = 'category_edit.html'
    form_class = CategoryEditForm
    success_url = reverse_lazy('manager:categories')

    def form_valid(self, form):
        """ Verify if the form is valid, and then save it """

        form.save()
        return super(CategoryEditView, self).form_valid(form)

    def get_object(self, queryset=None):
        """ Returns the category instance based on the id given """

        id = self.kwargs.get('id', None)
        instance = get_object_or_404(Category, id=id)
        return instance


class CategoryDeleteView(DeleteView):
    """ View for deleting a specific category instance """

    template_name = 'confirm_delete.html'
    model = Category
    success_url = reverse_lazy('manager:categories')


class ProductsManagementView(ListView):
    """ ListView for the Product model administration """

    template_name = 'products_management.html'
    context_object_name = 'products'

    def get_queryset(self):
        """ Returns the list of product instances """

        queryset = Product.objects.all()
        return queryset


class ProductEditView(UpdateView):
    """ View for editing a specific product instance """

    template_name = 'product_edit.html'
    form_class = ProductEditForm
    success_url = reverse_lazy('manager:products')

    def form_valid(self, form):
        """ Verify if the form is valid, and then save it """

        form.save()
        return super(ProductEditView, self).form_valid(form)

    def get_object(self, queryset=None):
        """ Returns the category instance based on the slug given """

        slug = self.kwargs.get('slug', None)
        instance = get_object_or_404(Product, slug=slug)
        return instance


class ProductDeleteView(DeleteView):
    """ View for deleting a specific product instance """

    template_name = 'confirm_delete.html'
    model = Product
    success_url = reverse_lazy('manager:products')

src/manager/templates/categories_management.html
{% extends 'manager_base.html' %}
{% load i18n %}
{% block title %}
  {% trans 'ManagerModule' %}
{% endblock title %}
{% block content %}
  <h1>{% trans 'Categories' %}</h1>
  <a href="{% url 'manager:category-create' %}">{% trans 'NewCategory' %}</a>
  <table border="1px">
    <tr>
      <th>ID</th>
      <th>{% trans 'Description' %}</th>
      <th>{% trans 'Edit' %}</th>
      <th>{% trans 'Delete' %}</th>
    </tr>
    {% for category in categories %}
    <tr>
      <td>{{ category.id }}</td>
      <td>{{ category.description }}</td>
      <td>
        <a href="{% url 'manager:category-edit' category.id %}">{% trans 'Edit' %}</a>
      </td>
      <td>
        <a href="{% url 'manager:category-delete' category.id %}">{% trans 'Delete' %}</a>
      </td>
    </tr>
    {% endfor %}
  </table>
{% endblock content %}

src/manager/templates/category_edit.html
{% extends 'manager_base.html' %}
{% load i18n %}
{% block content %}
  <form method="post" enctype="multipart/form-data">{% csrf_token %}
	    {{ form.as_p }}
	    <input type="submit" value="{% trans 'Save' %}">
  </form>
{% endblock content %}

src/manager/templates/confirm_delete.html
{% load i18n %}
<form method="post">{% csrf_token %}
  <p>{% trans 'AreYouSureYouWantToDelete' %} "{{ object }}"?</p>
  <input type="submit" value="{% trans 'Confirm' %}">
</form>

src/manager/templates/index.html
{% extends 'manager_base.html' %}
{% load i18n %}
{% block title %}
  {% trans 'ManagerModule' %}
{% endblock title %}
{% block content %}
  <a href="{% url 'manager:categories' %}">{% trans 'Categories' %}</a><br/>
  <a href="{% url 'manager:products' %}">{% trans 'Products' %}</a>
{% endblock content %}

src/manager/templates/manager_base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>
  {% block title %}
    {% trans 'ManagerModule' %}
  {% endblock title %}
  </title>
</head>
<body>
  <a href="{% url 'website:index' %}">{% trans 'HomePage' %}</a><br/>
  <hr>
  <h1 align="center">{% trans 'ManagerModule' %}</h1>
  <hr/>
  {% block content %}
  {% endblock content %}
</body>
</html>

src/manager/templates/product_edit.html
{% extends 'manager_base.html' %}
{% load i18n %}
{% block title %}
  {% trans 'ProductEdit' %}
{% endblock title %}
{% block content %}
<form method="post" enctype="multipart/form-data">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="{% trans 'Save' %}">
</form>
{% endblock content %}

src/manager/templates/products_management.html
{% extends 'manager_base.html' %}
{% load i18n %}
{% block title %}
  {% trans 'ManagerModule' %}
{% endblock title %}
{% block content %}
  <h1>{% trans 'Products' %}</h1>
  <a href="{% url 'manager:product-create' %}">{% trans 'NewProduct' %}</a>
  <table border="1px">
    <tr>
      <th>{% trans 'Barcode' %}</th>
      <th>{% trans 'Title' %}</th>
      <th>{% trans 'Edit' %}</th>
      <th>{% trans 'Delete' %}</th>
    </tr>
    {% for product in products %}
    <tr>
      <td>{{ product.barcode }}</td>
      <td>{{ product.title }}</td>
      <td>
        <a href="{% url 'manager:product-edit' product.slug %}">{% trans 'Edit' %}</a>
      </td>
      <td>
        <a href="{% url 'manager:product-delete' product.slug %}">{% trans 'Delete' %}</a>
      </td>
    </tr>
    {% endfor %}
  </table>
{% endblock content %}